### ISSUE TITLE
Giao diện Pharmacist (🫅 - ưu tiên)

### ISSUE THREAD

**Issue by clgslsm** [clgslsm/HMS-by-Haskell-Clown#25]
Giao diện Pharmacist: Quản lí thuốc. Create delete updare medicine. Sắp xếp các medicine theo hạn sử dụng (Hàng đầu là thuốc gần đến hết hạn sử dụng nhất)

**Comment by TinnieTheCat198** [comment]
Issue has been generally completed - The work is on branch Pharmacist-UI
I haven't implement sorting medicine as the description. Instead, I use table filter to filter out which medicine are near to expiry date (within 14 days)

**Comment by clgslsm** [comment]
Solving
